guardian/recipes

.github/workflows/ci.yml
build.sbt
scripts/ci-js
scripts/ci-sbt

Run CI steps in GitHub Actions.
Requires https://github.com/guardian/pan-domain-authentication/pull/75.
n/a
CI checks are in place.
n/a
n/a

add github action for ci

---

build.sbt
cloudformation.yaml
project/plugins.sbt
riff-raff.yaml
scripts/ci

Make this project RIffRaff deployable:
- add the `sbt-riffraff-artifact` plugin
- add a cloudformation template
- add a `riff-raff.yaml` file
Having this in place allows us to see changes in an AWS environment 🎉 . Currently, there's only a PROD stack deployed.
The majority of this diff was taken from [typerighter](https://github.com/guardian/typerighter).
TODO:
Deploy it?
CI/CD is fully in place for this app.
n/a
n/a

add riffraff support

---

app/AppLoader.scala
app/config/Config.scala
app/logging/LogConfig.scala
build.sbt
cloudformation.yaml

Ship logs to Central ELK to improve observability of behaviour.
- Deploy branch
- Observe logs in Central ELK

Ship logs to Central ELK

---

app/controllers/HomeController.scala
conf/routes
package-lock.json
package.json
recipes-client/components/recipe-component.tsx
recipes-client/components/recipe.tsx
recipes-client/data/recipe-schema.ts
recipes-client/data/recipe.ts
recipes-client/index.tsx
recipes-client/pages/curation.tsx
recipes-client/pages/home.tsx

-Added new component `RecipeComponent` that recursively parses recipe JSON and creates a form text field for each item. This allows displaying the data extracted from a recipe.
-Updates Recipe JSON schema. Specifically, cook/prep times now has key-value pairs instead of a list of strings.
Just run as normal.

Feature: Added RecipeComponent.

---

app/controllers/ApiController.scala
package-lock.json
package.json
recipes-client/components/recipe-component.tsx
recipes-client/components/recipe.tsx
recipes-client/consts/index.ts
recipes-client/data/recipe-schema.ts
recipes-client/index.tsx
recipes-client/pages/curation.tsx
recipes-client/pages/home.tsx

Client now requests recipe data and schema from Play API [stub data].
https://trello.com/c/QXvewyZK/165-server-endpoint-to-return-recipe-json
Run it locally and see whether form on the left is populated

Ms ui request api

---

app/controllers/ApiController.scala
package-lock.json
package.json
recipes-client/components/form-group.tsx
recipes-client/components/form-item.tsx
recipes-client/components/recipe-component.tsx
recipes-client/components/recipe.tsx
recipes-client/consts/index.ts
recipes-client/data/recipe-schema.ts
recipes-client/data/recipe.ts
recipes-client/index.tsx
recipes-client/pages/curation.tsx
recipes-client/pages/home.tsx

Better `form` display of the RecipeComponent.
Run locally as per instructions.

Better recipe form display

---

app/controllers/HomeController.scala

Reinstate `PanDomainAuthentication` to allow `ApiAuthAction` on `BaseController`.

Fix: reinstate `PanDomainAuthentication` mixin.

---

README.md
app/controllers/ApiController.scala
app/controllers/ProxyController.scala
cloudformation.yaml
recipes-client/components/comment-highlighter.tsx
recipes-client/components/form-group.tsx
recipes-client/components/form-item.tsx
recipes-client/components/gu-capi-frame.tsx
recipes-client/components/recipe-component.tsx
recipes-client/consts/index.ts
recipes-client/interfaces/main.tsx
recipes-client/interfaces/ui.tsx
recipes-client/pages/home.tsx
recipes-client/reducers/recipe-reducer.tsx
recipes-client/utils/colours.ts
recipes-client/utils/highlighting.spec.ts
recipes-client/utils/highlighting.ts
recipes-client/utils/html-parsing.spec.ts
recipes-client/utils/html-parsing.ts
recipes-client/utils/ordering.tsx
recipes-client/utils/test-fixtures.ts

A lot of issues flagged up in the [expert user testing session](https://docs.google.com/spreadsheets/d/1zEgFQ30GA255cpo19684iYSMCAMRxoyzdF-au3Z5-ik)
Run unit tests to check regex matching using `npm run test`
Are the same issue still seen?
No risks, database updated to new data model.

Fix outstanding from first review/user testing

---

recipes-client/components/form-group.tsx
recipes-client/components/gu-capi-frame.tsx
recipes-client/components/recipe-component.tsx
recipes-client/consts/index.ts
recipes-client/interfaces/main.tsx
recipes-client/interfaces/ui.tsx
recipes-client/reducers/recipe-reducer.tsx
recipes-client/utils/ordering.tsx

Adding an ingredient by pressing "+" under it now correctly adds an new empty ingredient in the form.
Run locally, select any recipe and add an ingredient clicking on the '+' button.
Does it still crash when adding ingredients?
🔘 👀

Fix crash when adding ingredient

---

cloudformation.yaml

Fixed a YAML indentation error introduced in #34

YAML is gr8!

---

riff-raff.yaml

Updates nase AMI to focal. Bionic is shortly out of support
Deploy, sense check & verify log output
-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
-   [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboard)
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast)
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour)

Update base API to focal

---

.github/workflows/ci.yml
build.sbt
project/plugins.sbt
riff-raff.yaml
scripts/ci
scripts/ci-js
scripts/ci-sbt

Working GitHub Actions to replace TeamCity build steps.
Post merge, GH will build the package and notify RiffRaff the same way as TC used to do.
Post merge, the TC project can be deleted.
**Note**: I had to revert commit https://github.com/guardian/recipes/commit/700db81969fb42970199e0a11f221c279012fa8b (new table schema) to get it to deploy via RiffRaff which I have subsequently removed again. In it's current form it will **_not_** deploy.
No more TC needed. 🙃

Working GitHub Actions 🤖

---

app/model/Recipe.scala
recipes-client/components/footer.tsx
scripts/fill.js

This address some mistakes in the back where the recipe class wasn't expecting the right shape. Now it is!
We've also taken the opportunity to add a curated recipe DB to the dev setup so local development is more representative of the tool in production.

Fix Recipe type check in the backend

---

.github/workflows/ci.yml

Updates CI.yaml config to build the main branch whenever it's updated (i.e. a PR is merged). Configured continuous deployment separately in RiffRaff

Continuous main builds

---

recipes-client/components/preview/data-preview.tsx

Put a space between amounts and 'tsp' or 'tbsp'

---

recipes-client/components/preview/data-preview.tsx

This reverts commit 13242d5ea32a2fc0e2e32b51bed70f78e9ce2d01.
-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
-   [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboard)
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast)
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour)

Revert "Update data-preview.tsx"

---

.gitignore
recipes-client/components/form/form-group.tsx
recipes-client/components/form/form-image-picker.tsx
recipes-client/components/form/form-item.tsx
recipes-client/components/form/inputs/ingredients.tsx
recipes-client/components/form/inputs/instructions.tsx
recipes-client/components/form/inputs/range.tsx
recipes-client/components/form/inputs/serves.tsx
recipes-client/components/form/inputs/timings.tsx

Make a number of changes to the editing form UI to make it more readable.
Still needs a number of improvements (e.g. display min/max fields for ingredients even if they are null so they can be edited if needed) but will raise them as separate PRs.

Improve form UI

---

recipes-client/components/footer.tsx
recipes-client/components/form/form-buttons.tsx
recipes-client/components/form/form-group.tsx
recipes-client/components/form/form-input-handlers.tsx
recipes-client/components/form/inputs/ingredients.tsx
recipes-client/components/form/inputs/instructions.tsx
recipes-client/components/form/inputs/serves.tsx
recipes-client/components/form/inputs/timings.tsx
recipes-client/components/preview/data-preview.tsx
recipes-client/components/recipe-component.tsx
recipes-client/consts/index.ts
recipes-client/interfaces/main.tsx
recipes-client/interfaces/ui.tsx
recipes-client/reducers/recipe-reducer.tsx
recipes-client/utils/html-parsing.ts
recipes-client/utils/ordering.tsx
recipes-client/utils/recipe-field-checkers.tsx

Noticed some types/interfaces with lowercase starting letter, which makes them look like variable names.

correct some casing on types/interfaces

---

recipes-client/components/form/form-buttons.tsx
recipes-client/consts/index.ts
recipes-client/interfaces/nastyHardcodedSchemas.tsx

As with #75 this adds buttons to add method steps when the field is empty.

Buttons for method when empty

---

package-lock.json
package.json
recipes-client/pages/curation.tsx

To minimise the risk of stale browsers overriding latest changes on a recipe age, redirect to Home page if the user has been idle for more than 2 minutes (alert box at 1 minute mark to confirm). The PR also increases the auto save interval from 20s to 60s.

Redirect on idle and increase autosave interval (20s -> 60s)

---

recipes-client/components/form/inputs/instructions.tsx
recipes-client/reducers/recipe-reducer.tsx

- Increments step number (currently only works if added to the last step)
- Do not display images field in the form
- Images field are added as `null` in the data

Refine instructions to increment step number and filter out images field

---

recipes-client/components/curation/curation-options-bar.tsx

Show alerts when a recipe saves or fails for quicker feedback to the reviewer

Show save success/failures

---

app/controllers/ApiController.scala

Add Benjamina Ebuehi contributor tag to dropdown options

---

app/controllers/ApiController.scala

Add Ravneet Gill contributor tag to dropdown options

---

app/controllers/ApiController.scala

To reflect the latest batch added to Hatch

Add a few more contributor tag options

---

app/controllers/ApiController.scala
recipes-client/components/dashboard/recipe-list.tsx
recipes-client/pages/home.tsx

Revert "Adjust what 'Edited' means in homepage dashboard"

---

app/controllers/ApiController.scala
recipes-client/components/form/inputs/timings.tsx

Adding a few contributors plus additional meal types and timings qualifiers based on feedback from editorial

More dropdown options

---

app/controllers/ApiController.scala

This adjusts the DynamoDB fetching logic responsible for the endpoint that lists all the recipe details on the Hatch dashboard. The app-ready count has sat at around 240 for a while now because we've likely hit the 1MB default cap.
By recursing over the results we ensure we get everything.

Paginate DynamoDB results

---

app/controllers/ApiController.scala

Tom Hunt,  Ravinder Bhogal and Jose Pizarro as requested by Anna B.

Add contributor dropdown options
