app/AppComponents.scala, app/controllers/ApiController.scala, conf/routes
Adds two endpoints in the Play App for serving recipes data and schema in JSON format (stubs only atm).
Follow local testing instruction in Readme file.
It serves stub JSON.
=> Feature: Added data and schema serving routes in API.

README.md
We've created a new permission in Janus which gives access to the specific resources needed for login.gutools. This has resulted in needing a single set of Janus credentials, rather than two.
Follows https://github.com/guardian/login.gutools/pull/48.
Follow the docs to run the app.
Simpler requirements to run the app locally.
n/a
n/a
=> use new Janus permission

app/config/Config.scala, app/controllers/ApiController.scala, app/controllers/ProxyController.scala, conf/application.conf, conf/routes
Adds endpoint to list recipe ids given `path`
Adds endpoint to get recipe data given `path`
Endpoint can now cope with `path`_`id` structure and correctly select recipe of article.
Run locally and `GET`:
`https://recipes.local.dev-gutools.co.uk/api/list/lifeandstyle/2012/jun/15/lettuce-recipes-hugh-fearnley-whittingstall`
`https://recipes.local.dev-gutools.co.uk/api/list`
`https://recipes.local.dev-gutools.co.uk/api/db/lifeandstyle/2012/jun/15/lettuce-recipes-hugh-fearnley-whittingstall_2`
Does it serve the correct recipe?
Yep
=> API endpoints: list recipes, get recipe ids for path

cloudformation.yaml
This PR adds some actions to the recipes cfn, required for Wazuh to function correctly. The image already contains the agent required (`editorial-tools-xenial-java8`)
[Guardian Wazuh guide](https://github.com/guardian/security-hq/blob/main/hq/markdown/wazuh.md)
Deploy to CODE, check Wazuh is reporting healthy by using SSM:
```ssm cmd -c "service wazuh-agent status | grep Active && journalctl -u wazuh-agent | grep Valid" -t <app tag>,CODE -p media-service```
=> Add permissions for wazuh agent

cloudformation.yaml
#23 neglected to add a security group allowing the [appropriate egress](https://github.com/guardian/security-hq/blob/main/hq/markdown/wazuh.md) for Wazuh. This PR adds it.
Issuing the following command should show a healthy agent on each box. (For some reason, the tag lookup doesn't work!)
```ssm cmd -c "service wazuh-agent status | grep Active && journalctl -u wazuh-agent" -i <instanceIds> -p composer```
<details>
<summary>Tested in PROD (in the absence of a CODE or equivalent)</summary>
```
========= i-xxx =========
STDOUT:
Active: active (running) since Thu 2021-04-08 17:09:10 UTC; 1min 36s ago
Apr 08 17:09:03 ip-10-248-203-248 authenticate-with-wazuh-manager.sh[1178]: 2021/04/08 17:09:03 agent-auth: INFO: Valid key created. Finished.
STDERR:
========= i-xxx =========
STDOUT:
Active: …
```
=> Add Wazuh security group

cloudformation.yaml
Alters the project CFN to use [IMDSv2](https://github.com/guardian/security-hq/blob/main/hq/markdown/guardduty-sechub-common-problems.md)
The app should work as before. When deployed, IMDSv1 usage should stop.
=> Add imdsv2 to instance profile

cloudformation.yaml
Following a discussion with @michel-ds we need a way of preserviing the original recipe that was imported into the app. One way of doing this is to store all edits in a separate table, then in the backend when a recipe is loaded to fetch it from the edited table if it's available, and from the other table if not. All writes go to the edited table. 
This is a proposal as much as a PR, happy to hear other options
=> Add table for edited recipes

riff-raff.yaml
Moves AMI from Xenial to Bionic because Xenial is no longer supported.
Related card [here](https://trello.com/c/NLpikw2C/2330-update-xenial-amis-to-use-bionic).
There is no CODE branch so we will need to deploy this at a time with low activity to ensure it's working (there are misleading CODE deploys on RiffRaff but there is in fact no CODE environment).
=> Moved Xenial AMI to Bionic as it is no longer being supported

cloudformation.yaml
Bug fix. 
Rename the table that stores edited recipes. The recipe and edited recipe tables were previously called the same name which triggered the following error during deploy.
```
EditedRecipesDynamoTable(AWS::DynamoDB::Table}: CREATE_FAILED recipes already exists in stack arn:aws:cloudformation:eu-west-1:743583969668:stack/recipes-PROD/8fda9450-edbd-11ea-9a83-0655dfaca74c
```
Does it deploy without error and create two dynamoDB tables?
App properly deployed again.
✔️ 
No UI changes.
=> Fix: Rename edited recipes table to avoid duplication.

package-lock.json, package.json, recipes-client/components/footer.tsx, recipes-client/utils/json-csv.ts
Adds a 'download CSV' button that allows user to download a (comma-separated) list of ingredients highlighted in the recipe.
Pick a recipe and click on the  'Download CSV' button to download the file.
No risks.
**Before**:
**After**:
=> Export ingredients to CSV file

cloudformation.yaml
Adds a [deletion policy](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html) to prevent accidental data loss from stack deletion
=> Add deletionpolicy to prevent data loss

build.sbt, project/build.properties, project/plugins.sbt
On 9 Dec 2021, a popular Java logging library log4j was discovered that
results in Remote Code Execution (RCE) by logging a certain string.
Here is helpful information on how the exploit works:
https://www.lunasec.io/docs/blog/log4j-zero-day/#how-the-exploit-works.
This Google doc explains how to secure our apps:
https://docs.google.com/document/d/1nVKsXiEXLviHOMY1iQEoyacvN93_SYCQwsOFfaP-dxo/edit#
Bumps `sbt` and `logstash-logback-encoder` to fix log4j vulnerability described above.
Follow installation instructions in `README.md` and run `sbt run` which should output the following line
```[info] welcome to sbt 1.5.7 ```
Does it still deploy successfully?
I can still find mentions of log4j versions < 6.8.21 in the `classpath` in the `project/.bloop/curationui-build.json` file after …
=>  Updates to sbt and log4j due to vulnerability

build.sbt
Bumps pan-domain-auth to 1.0.6 to patch some security vulnerabilities.
The app should continue to accept authenticated requests, and reject unauthenticated ones.
=> Bump pan-domain-auth to 1.0.6

.github/workflows/ci.yml, app/controllers/ManagementController.scala, app/logging/LogConfig.scala, build.sbt, conf/routes, scripts/ci-sbt
My bad. Forgot that `BuildInfo` is no longer available after stripping out the riff-raff artifact library, hence removing obsolete references to BuilInfo.
=> Remove old BuildInfo

app/controllers/ApiController.scala, app/model/Recipe.scala, recipes-client/components/footer.tsx, recipes-client/components/recipe-list.tsx, recipes-client/pages/curation.tsx, recipes-client/pages/home.tsx
This adjusts the /api/list and /api/db/*id endpoints to check both the raw and curated recipe data tables then preferring the curated versions where they exist. There are a few key benefits to this:
- The homepage can now display whether a given recipe has been marked app-ready or not (I've taken the opportunity to make the page as a whole easier on the eye.
- When users go to the curation view they will be met with the edited - and so most up to date - data. Before it would show the raw version regardless
- Curation pages can autosave and refetch data, allowing changes to be reflected in close to real time
In the UI I've tested this by toggling the `isAppReady` field, saving the recipe, then seeing the change reflected in the homepage summary view. You can also check the endpoints …
=> Check both raw and curated tables in appropriate API requests

app/controllers/ApiController.scala, app/model/Recipe.scala, recipes-client/components/form/form-group.tsx, recipes-client/components/form/inputs/serves.tsx, recipes-client/consts/index.ts, recipes-client/utils/recipe-field-checkers.tsx
This adjusts the schema to expect an array of serves objects rather than just one. The UI generation has been changed to reflect this and I've taken the opportunity to update the dropdown options and hide noisy/unnecessary/contentious fields ahead of editorial having a crack at some curation next week.
=> Rewire schema for serves array

package-lock.json, package.json, recipes-client/components/app-ready-status.tsx, recipes-client/components/form/form-image-picker.tsx, recipes-client/components/preview/data-preview.tsx, recipes-client/components/recipe-component.tsx, recipes-client/components/recipe-list.tsx, recipes-client/consts/index.ts, recipes-client/interfaces/main.tsx, recipes-client/pages/curation.tsx
As requested by Anna B, this adds a option to view a plaintext summary of recipe data on curation pages. Now when users select a recipe to edit they will be met with the summary on the right rather than the form. To get to the form they select the 'Edit' tab.
This takes advantage of the `Tabs` component from [`source-react-components-development-kitchen `](https://github.com/guardian/csnx/tree/main/libs/%40guardian/source-react-components-development-kitchen) courtesy of @guardian/client-side-infra, which I think makes for a pretty smooth UI.
No doubt there is room for further improvement here but it's a feature is was keen to get live. It should make it much easier for editorial to scan recipe data and spot missing/iffy fields.
=> Add data summary view to curation page

.github/workflows/ci.yml, .gitignore, project/plugins.sbt, public/.prout.json
Add [PRout](https://github.com/guardian/prout) configuration. We opted for a simple static file generated at CI time rather than using SBTBuildInfo. We've removed the dependency accordingly as it wasn't being used.
=> Set up PRout

build.sbt, project/plugins.sbt
Assets didn't have hashes and so were cached, which meant users wouldn't get the latest changes promptly.
Some of the steps from
https://www.playframework.com/documentation/2.4.x/Assets#Reverse-routing-and-fingerprinting-for-public-assets were already done (from long ago) but needed to add the `sbt-digest` plugin then reference in the `pipelineStages` in the `build.sbt`.
=> cache assets effectively: add hashes to assets (notably `index.js`)

app/controllers/ApiController.scala, app/model/Recipe.scala, recipes-client/interfaces/main.tsx, recipes-client/interfaces/nastyHardcodedSchemas.tsx
Update the schema to reflect changes agreed on by Basecamp, D&I, CoPip, and Editorial. Ingredient and Serves objects now include the original text
=> Add original text fields to schema

app/controllers/ApiController.scala, recipes-client/components/preview/data-preview.tsx
This tweaks the presentation of ingredients in preview mode based on feedback from Anna B.
Now:
- An 'x' is inserted between the amount and the unit when the unit involves tins
- No space between amount and unit
I've also added Anna Jones to the list of contributor options ahead of some rhubarb recipes dropping into the raw database.
=> Ingredient preview adjustments

recipes-client/components/dashboard/recipe-list.tsx, recipes-client/pages/home.tsx
With recipe data starting to flow into Hatch it felt like time to give users control over the homepage. This PR adds filters for all, curated, and non-curated recipes:
I've also chucked in an app-ready counter in the top right hand corner as that seemed like a nice thing to give visibility.
=> Filter displayed recipes on dashboard

app/controllers/ApiController.scala, app/model/Recipe.scala, recipes-client/components/preview/data-preview.tsx, recipes-client/interfaces/main.tsx
Also restore displaying cuisines in preview (see https://github.com/guardian/recipes/pull/60) and adds `text` field to servings. I also realised `suitableForDietIds` wasn't in the backend model and so wasn't making it into the curated database. This has been fixed.
=> Add `composerId` and `webPublicationDate` to model

cdk/lib/__snapshots__/recipes.test.ts.snap, cdk/lib/recipes.ts
We're having an issue where visitors to Hatch occasionally get 502 errors. One potential reason for this is the instance size being too small. Given the current one is a SMALL T3 this seemed like a sensible thing to try.
Will also be turning on CloudWatch agent as suggested by @akash1810.
=> Bump up instance size from `SMALL` to `MEDIUM`

recipes-client/pages/home.tsx
This wraps the fetch request to the recipes list endpoint so that it doesn't get stuck in an infinite loop.
=> Prevent infinite fetch on homepage

app/model/Recipe.scala, recipes-client/components/preview/data-preview.tsx
This addresses an issue raised by Anna B where featured images selected in the Hatch UI weren't being saved to the curated database. This was because the updated `featuredImage` field wasn't fully represented in the backend. 
This has been fixed, and a link to the original Grid image is now included in the summary view, like so:
This isn't the first time something's slipped through the net (see https://github.com/guardian/recipes/pull/62). I'd like like to tighten/unify the types somehow, or at least test more thoroughly going forward as this kind of human error could lead to a lot of good data being lost once curation ramps up.
=> Add `featuredImage` field to backend model, display in summary UI

app/controllers/ApiController.scala, app/model/Recipe.scala, conf/routes, recipes-client/components/footer.tsx, recipes-client/components/preview/data-preview.tsx, recipes-client/interfaces/main.tsx, recipes-client/pages/home.tsx
This adjusts the endpoints in the backend so that the 'Reset' button works as desired (reverting the recipe to its raw ML form) and adding a final confirmation check after the button is pressed so users know what they're getting themselves into.
Also a couple of other tweaks - showing dashes in the data preview when `featuredImage` is empty and changing `onClick` to `onChange` for the homepage radio buttons.
=> Data reset endpoint and UI confirmation check

.github/workflows/ci.yml, app/controllers/HomeController.scala, app/views/index.scala.html, recipes-client/components/curation/pinboard-track-and-preselect.tsx, recipes-client/pages/curation.tsx
Co-authored-by: @frederickobrien 
https://trello.com/c/ryaNbPFY/1866-pinboard-in-recipeasy
@pradasa and @frederickobrien had the wonderful idea to add [Pinboard](https://github.com/guardian/pinboard) to the Recipeasy app, where journalists (freelancers most likely) will be vetting the AI generated structured data before approving - this will likely generate some discussion for some pieces… what better place than [Pinboard](https://github.com/guardian/pinboard).
As per usual adding Pinboard to the tool was just a matter of adding the script tag (see `app/views/index.scala.html`).
However, in order to have dedicated pinboard chats per recipe, each underlying composer piece needs to be tracked in workflow (which also gives the benefit of being able to be across all the 'Recipe Data' …
=> Pinboard 📌

recipes-client/components/preview/data-preview.tsx
As requested by @guardian-ben, this updates the data preview component to display a recipe's ID and provide a link to the canonical article. 
As the interplay between Hatch, CoPip, and the app continues to grow it's handy to have this visible.
=> Display recipe ID and canonical article in summary view

app/controllers/ApiController.scala, app/model/Recipe.scala, recipes-client/components/form/form-image-picker.tsx, recipes-client/components/preview/data-preview.tsx, recipes-client/interfaces/main.tsx, recipes-client/pages/curation.tsx
Following discussions among @guardian/basecamp and @guardian/content-platforms about what's needed from the `featuredImage` field for recipe data, this adjusts the model and UI to expect rich objects rather than strings.
The UI has also been improved, with the data preview displaying the chosen image.
There is scope to follow up on this with a PR taking advantage of existing Pinboard integration (#65). At present image options are still limited to those that appear in the recipe's canonical article. Longer term we want users to be able to use any image from the grid. Using the drag and drop loveliness of Pinboard this feels very doable.
Before this can be safely merged the curated data needs to have its `featuredImage` fields cleared.
=> Store `featuredImage` objects  instead of Grid IDs as strings

recipes-client/components/preview/data-preview.tsx
As requested by Anna B this adds more custom rules for ingredients in the data preview section of curation pages. Fractions will be presented more naturally (e.g. `1.5` will be displayed as '1½'.
As ever probably not the most elegant solution but it should capture a huge majority of cases. The goal is to make curating as smooth as possible and these changes move the needle.
=> More natural unit presentation in data preview

recipes-client/components/form/form-buttons.tsx, recipes-client/components/form/inputs/instructions.tsx, recipes-client/consts/index.ts, recipes-client/interfaces/main.tsx
As raised by Anna B, users had no way of adding them if there were none there. Not good!
Now they can:
=> Buttons to add and remove timings

app/controllers/ApiController.scala
I noticed weird behaviour where not all the recipes were appearing in the Hatch dashboard. Visiting individual recipe pages putting the missing ids in the URL works fine so I think the issue was a cap on the number of items scanned.
This has been removed and will hopefully translate to all recipes being fetched and displayed in the Hatch dashboard.
=> Remove DynamoDB scan request limit

cdk/bin/cdk.ts, cdk/lib/__snapshots__/recipes.test.ts.snap, cdk/lib/recipes.test.ts, cdk/package-lock.json, cdk/package.json
This PR allows us to start backing up the `recipes` app's DynamoDB tables using https://github.com/guardian/aws-backup. For more details on this project see [this doc](https://docs.google.com/document/d/11EZtuVHCnjavE9AYLroiuDUsMzbp2ulFBtj4VkyCKNc/edit).
N.B. prior to enabling the backups I upgraded GuCDK and refactored a bit to improve the coverage of the snapshot tests; it will be easiest to review this PR commit by commit.
The snapshot change in https://github.com/guardian/recipes/commit/9314f57bfea23515f3e8862756734a8a8cca5724 should be sufficient here.
I will also check that the backups are created as expected after this has been deployed (the backup jobs run overnight so I'll report back the next working day after this is merged).
We will be able to recover (most) data stored in …
=> Enable nightly backups for DynamoDB tables

recipes-client/components/preview/data-preview.tsx
The data model returns an amount of 0.13 for eighths (of a teaspoon or some such) so this adds a catch condition in the data preview to display a more editorially consistent fraction in the data preview:
=> Add ⅛ prettification to data preview

recipes-client/components/form/form-buttons.tsx, recipes-client/components/form/inputs/serves.tsx, recipes-client/components/preview/data-preview.tsx, recipes-client/consts/index.ts, recipes-client/interfaces/nastyHardcodedSchemas.tsx
Like #75 and #80, this addresses an issue where servings couldn't be added if there wasn't at least one in the dataset. 
Now there are buttons that just plop one on the end.
Based on feedback from Anna B the unit input has been changed from a dropdown of preset 'people' or 'units' options to accommodate more nuanced information (like 20 'small cupcakes' or 1 '20cm cake', etc.)
=> Standalone servings +/- buttons

app/controllers/ApiController.scala, recipes-client/components/dashboard/recipe-list.tsx, recipes-client/components/preview/data-preview.tsx, recipes-client/components/reusables/app-ready-status.tsx, recipes-client/pages/home.tsx
Following feedback from Anna B we wanted to provide more differentiation on recipe status than a binary app-ready/not app-ready, so that curators can keep track of recipes they've edited but aren't ready to go into the app.
To that end this PR adds an `isInCuratedTable` field to the /list endpoint, which means we can display when a recipe has been edited (i.e. saved to the curated DynamoDB table) but not yet marked app-ready.
I've updated the dashboard filtering accordingly so users can quickly isolate in progress recipes. 
I've also taken the opportunity to tidy up what's displayed in the 'Author(s)' column. Since we shifted to contributor tags we've been displaying them, and nothing at all if the field is empty:
Now we pull through both contributor and byline info and fall back to the …
=> Display recipe edit status in dashboard

recipes-client/pages/home.tsx
Adds a logic change I missed in #83. This creates the desired behaviour of displaying recipes that have not been marked app-ready and do not appear in the curated table (the latter should be enough but no harm in checking both)
=> Fix 'Awaiting curation' homepage filter conditions

recipes-client/components/form/form-item.tsx
This restores behaviour in form dropdown fields where the field is empty when generated. As flagged by editorial there have been instances where the first field happens to display the desired input but because it's not being selected explicitly that wasn't translating to the data.
By putting an empty string at the front of the list of options users have to explicitly select values.
=> Make dropdowns empty as default

recipes-client/components/form/inputs/timings.tsx
Following on from #85 this adds a few more timing qualifier options.
=> More serving dropdown options

recipes-client/components/dashboard/recipes-overview.tsx, recipes-client/components/dashboard/welcome-explainer.tsx, recipes-client/pages/home.tsx
This adds a modest summary of the curated data to the Hatch homepage. As a first pass it displays the number of app-ready recipes per top chef and what percentage of the overall count they are.
Screenshot below is of it running locally so the value isn't so clear but you get the gist:
The hope with this change is that editorial will have a birds-eye view of the curated data and can prioritise work / recipe structuring requests based on imbalances in the data.
=> Mini data dashboard summary of curated recipes

app/controllers/ApiController.scala, recipes-client/components/dashboard/recipe-list.tsx, recipes-client/pages/home.tsx
This changes the logic behind recipes being 'Edited'. Before it meant the recipe appeared in the curated database, now it means the description field in the raw and curated version are different. Feels a smidge hacky but should be more useful to editorial
=> Adjust what 'Edited' means in homepage dashboard

app/controllers/ApiController.scala, app/model/Recipe.scala, recipes-client/components/form/form-buttons.tsx, recipes-client/components/form/inputs/timings.tsx, recipes-client/components/preview/data-preview.tsx, recipes-client/consts/index.ts, recipes-client/interfaces/main.tsx, recipes-client/reducers/recipe-reducer.tsx
This updates the recipe data model to expect ranges rather than numbers in the timings `durationInMins` field, and adds an under the hood conversion check as part of Hatch's save functionality.
Run locally, save recipes, and see if the duration field shape changes and saves as expected.
Recipe data model is consistent all through the D&I -> Hatch -> CoPip -> App pipeline.
As ever there is a wariness about messing with data integrity. Between nightly backups and strict type checking on anything going into DynamoDB hopefully we're safe here.
=> Adjust model and UI to shift `durationInMins` field from number to range

recipes-client/pages/curation.tsx
Increase timeout/redirect interval to 3 minutes (and prompt at 2 mins) at editorial request
=> Increase redirect timeout

recipes-client/components/curation/grid-selector.tsx, recipes-client/components/form/form-group.tsx, recipes-client/components/form/form-image-picker.tsx, recipes-client/components/layout/header.tsx, recipes-client/components/preview/data-preview.tsx, recipes-client/components/reusables/check-button.tsx, recipes-client/pages/curation.tsx, recipes-client/reducers/recipe-reducer.tsx
This PR integrates the Grid with Hatch, allowing curators to select and crop any image from its library when selecting featured images. Users can either select the '+' button in the curation view to open an iframe of the [Grid](https://github.com/guardian/grid), or drag and drop images from [Pinboard](https://github.com/guardian/pinboard).
The change means that curators will no longer be bound to the images that appear in a recipe's canonical article when selecting featured images. This has occasionally popped up as a problem because: 
- a) Sometimes recipes don't have an image
- b) The image(s) available don't look great on mobile and could do with being replaced/cropped
@twrichards has masterminded this as a standalone `WithGridSelector` component, which can be wrapped around other …
=> Grid integration

app/controllers/ApiController.scala, recipes-client/components/curation/pinboard-track-and-preselect.tsx, recipes-client/components/dashboard/recipe-list.tsx, recipes-client/components/form/form-group.tsx, recipes-client/pages/home.tsx, recipes-client/utils/workflow.ts
This PR uses Composer IDs to connect the worlds of Hatch and Workflow. By using the `composerId` field of the recipe data we're able to assign people to canonical articles, a change which should make multiple curators much more feasible. 
If someone is assigned to a recipe article in Workflow, that will surface in the Hatch dashboard for every recipe within that article. Recipes are now also grouped together based on whether they share the same canonical article.
The changes here build on work done while integrating Pinboard (#65) and together with (#114) leaves us well positioned to start onboarding other members of editorial if we want to. 
Run locally, change assignees to articles in CODE Workflow, and see if that reflects in Hatch. 
Clear assignee system for curating recipes that …
=> Workflow integration

recipes-client/components/dashboard/recipe-list.tsx
Addresses a bug that snuck through #119.
=> Handle undefined `composerId` field when sorting recipe list

recipes-client/components/curation/curation-options-bar.tsx, recipes-client/components/form/inputs/ingredients.tsx
This applies some feedback/suggestions from Chloe Kirton after shadowing Anna B. The PR applies a couple of small changes:
- The horizontal scroll bar has been moved to the top of each individual ingredient group, rather than the bottom of the overall section
- The successful save pop-up has been removed as the autosave was making it a frustration. It was implemented in part due to saving issues but it's been long enough since that's been a problem that this feels safe to remove
=> UI tweaks: Move horizontal scroll bar to top of ingredient sections, remove successful save popups
